<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUeRrPZX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUeRrPZX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUeRrPZX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUeRrPZX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUeRrPZX\App_KernelDevDebugContainer([
    'container.build_hash' => 'UeRrPZX',
    'container.build_id' => 'd8a626e9',
    'container.build_time' => 1707140617,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUeRrPZX');
